import tag as Tag

table = {
    'program': Tag.PROGRAM,
    'constant': Tag.CONSTANT,
    'var': Tag.VAR,
    'begin': Tag.BEGIN,
    'end': Tag.END,
    'writeln': Tag.WRITELN,
    'readln': Tag.READLN,
    'while': Tag.WHILE,
    'do': Tag.DO,
    'repeat': Tag.REPEAT,
    'until': Tag.UNTIL,
    'for': Tag.FOR,
    'to': Tag.TO,
    'downto': Tag.DOWNTO,
    'if': Tag.IF,
    'then': Tag.THEN,
    'else': Tag.ELSE,
    'not': Tag.NOT,
    'or': Tag.OR,
    'div': Tag.DIV,
    'mod': Tag.MOD,
    'and': Tag.AND,
    'integer': Tag.INTEGER,
    'real': Tag.REAL,
    'boolean': Tag.BOOLEAN,
    'string': Tag.STRING

}
symbols = {
    ';': Tag.DOTCOMMA,
    '.': Tag.DOT,
    '(': Tag.OPENPAR,
    ')': Tag.CLOSEPAR,
    '=': Tag.EQ,
    ':': Tag.DOBDOT,
    ',': Tag.COMMA,
    ':=': Tag.ASSIGN,
    '+': Tag.PLUS,
    '-': Tag.MINUS,
    '<>': Tag.MINGR,
    '<': Tag.MIN,
    '<=': Tag.MINEQ,
    '>': Tag.GR,
    '>=': Tag.GREQ,
    '*': Tag.MULT,
    '/': Tag.FRAC
}

non_terminals = [
    'START-P',
    'START',
    'PROGRAM-HEADING',
    'OPT-PROGRAM-PARAMETERS',
    'PROGRAM-PARAMETERS',
    'PROGRAM-BLOCK',
    'CONSTANT-DECLARATION-PART',
    'CONSTANT-DEFINITION',
    'MORE-CONSTANT-DEFINITION',
    'VARIABLE-DECLARATION-PART',
    'MORE-VARIABLE-DECLARATION',
    'VARIABLE-DECLARATION',
    'STATEMENT-PART',
    'TYPE',
    'IDENTIFIER-LIST',
    'MORE-IDENTIFIER',
    'STATEMENT-SEQUENCE',
    'MORE-STATEMENT',
    'STATEMENT',
    'SIMPLE-STATEMENT',
    'ASSIGNMENT-STATEMENT',
    'IO-STATEMENT',
    'WRITELN-STATEMENT',
    'OPT-ELEMENT-LIST',
    'ELEMENT-LIST',
    'MORE-ELEMENT',
    'ELEMENT',
    'READLN-STATEMENT',
    'OPT-IDENTIFIER-LIST',
    'STRUCTURED-STATEMENT',
    'COMPOUND-STATEMENT',
    'REPETITIVE-STATEMENT',
    'WHILE-STATEMENT',
    'REPEAT-STATEMENT',
    'FOR-STATEMENT',
    'TO-DOWNTO',
    'CONDITIONAL-STATEMENT',
    'OPT-ELSE',
    'EXPRESSION',
    'OPT-REL-EXPRESSION',
    'SIMPLE-EXPRESSION',
    'OPT-SIGN',
    'MORE-ADD-TERM',
    'TERM',
    'MORE-MULT-TERM',
    'FACTOR',
    'RELATIONAL-OPERATOR',
    'ADDITION-OPERATOR',
    'MULTIPLICATION-OPERATOR'
]

terminals = [
    'program',
    'constant',
    'var',
    'begin',
    'end',
    'writeln',
    'readln',
    'while',
    'do',
    'repeat',
    'until',
    'for',
    'to',
    'downto',
    'if',
    'then',
    'else',
    'not',
    'or',
    'div',
    'mod',
    'and',
    'integer',
    'real',
    'boolean',
    'string',
    'identifier',
    'number',
    ';',
    '.',
    '(',
    ')',
    '=',
    ':',
    ',',
    ':=',
    '+',
    '-',
    '<>',
    '<',
    '<=',
    '>',
    '>=',
    '*',
    '/',
    '$'
]
