import tag as Tag

table = {
    'program': Tag.PROGRAM,
    'constant': Tag.CONSTANT,
    'var': Tag.VAR,
    'begin': Tag.BEGIN,
    'end': Tag.END,
    'writeln': Tag.WRITELN,
    'readln': Tag.READLN,
    'while': Tag.WHILE,
    'do': Tag.DO,
    'repeat': Tag.REPEAT,
    'until': Tag.UNTIL,
    'for': Tag.FOR,
    'to': Tag.TO,
    'downto': Tag.DOWNTO,
    'if': Tag.IF,
    'then': Tag.THEN,
    'else': Tag.ELSE,
    'not': Tag.NOT,
    'or': Tag.OR,
    'div': Tag.DIV,
    'mod': Tag.MOD,
    'and': Tag.AND,
    'integer': Tag.INTEGER,
    'real': Tag.REAL,
    'boolean': Tag.BOOLEAN,
    'string': Tag.STRING

}
symbols = {
    ';': Tag.DOTCOMMA,
    '.': Tag.DOT,
    '(': Tag.OPENPAR,
    ')': Tag.CLOSEPAR,
    '=': Tag.EQ,
    ':': Tag.DOBDOT,
    ',': Tag.COMMA,
    ':=': Tag.ASSIGN,
    '+': Tag.PLUS,
    '-': Tag.MINUS,
    '<>': Tag.MINGR,
    '<': Tag.MIN,
    '<=': Tag.MINEQ,
    '>': Tag.GR,
    '>=': Tag.GREQ,
    '*': Tag.MULT,
    '/': Tag.FRAC
}

non_terminals = {
    'START-P': 46,
    'START': 47,
    'PROGRAM-HEADING': 48,
    'OPT-PROGRAM-PARAMETERS': 49,
    'PROGRAM-PARAMETERS': 50,
    'PROGRAM-BLOCK': 51,
    'CONSTANT-DECLARATION-PART': 52,
    'CONSTANT-DEFINITION': 53,
    'MORE-CONSTANT-DEFINITION': 54,
    'VARIABLE-DECLARATION-PART': 55,
    'MORE-VARIABLE-DECLARATION': 56,
    'VARIABLE-DECLARATION': 57,
    'STATEMENT-PART': 58,
    'TYPE': 59,
    'IDENTIFIER-LIST': 60,
    'MORE-IDENTIFIER': 61,
    'STATEMENT-SEQUENCE': 62,
    'MORE-STATEMENT': 63,
    'STATEMENT': 64,
    'SIMPLE-STATEMENT': 65,
    'ASSIGNMENT-STATEMENT': 66,
    'IO-STATEMENT': 67,
    'WRITELN-STATEMENT': 68,
    'OPT-ELEMENT-LIST': 69,
    'ELEMENT-LIST': 70,
    'MORE-ELEMENT': 71,
    'ELEMENT': 72,
    'READLN-STATEMENT': 73,
    'OPT-IDENTIFIER-LIST': 74,
    'STRUCTURED-STATEMENT': 75,
    'COMPOUND-STATEMENT': 76,
    'REPETITIVE-STATEMENT': 77,
    'WHILE-STATEMENT': 78,
    'REPEAT-STATEMENT': 79,
    'FOR-STATEMENT': 80,
    'TO-DOWNTO': 81,
    'CONDITIONAL-STATEMENT': 82,
    'OPT-ELSE': 83,
    'EXPRESSION': 84,
    'OPT-REL-EXPRESSION': 85,
    'SIMPLE-EXPRESSION': 86,
    'OPT-SIGN': 87,
    'MORE-ADD-TERM': 88,
    'TERM': 89,
    'MORE-MULT-TERM': 90,
    'FACTOR': 91,
    'RELATIONAL-OPERATOR': 92,
    'ADDITION-OPERATOR': 93,
    'MULTIPLICATION-OPERATOR': 94
}

terminals = [
    'program',
    'constant',
    'var',
    'begin',
    'end',
    'writeln',
    'readln',
    'while',
    'do',
    'repeat',
    'until',
    'for',
    'to',
    'downto',
    'if',
    'then',
    'else',
    'not',
    'or',
    'div',
    'mod',
    'and',
    'integer',
    'real',
    'boolean',
    'string',
    'identifier',
    'number',
    ';',
    '.',
    '(',
    ')',
    '=',
    ':',
    ',',
    ':=',
    '+',
    '-',
    '<>',
    '<',
    '<=',
    '>',
    '>=',
    '*',
    '/',
    '$'
]
